#Requires -Version 5.1
<#
.SYNOPSIS
    Packages the AnythingLLM Launcher into a distributable ZIP and a
    single-file self-extracting installer (PowerShell).
.DESCRIPTION
    Reads every launcher file, base64-encodes it, then writes two outputs:

      AnythingLLM_Launcher_v1.1.zip         <- traditional ZIP archive
      AnythingLLM_Launcher_Setup_v1.1.ps1   <- self-extracting installer
                                               (single file, no other deps)

    Run this script once to produce the distributables, then share either
    output file with users.
.EXAMPLE
    .\pack.ps1
    .\pack.ps1 -OutputDir C:\builds
#>
param(
    [string]$OutputDir = $PSScriptRoot,
    [string]$Version   = "1.1"
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$PackageName = "AnythingLLM_Launcher_v$Version"
$Root        = $PSScriptRoot

# ---------------------------------------------------------------------------
# Files to bundle (relative to the repo root)
# ---------------------------------------------------------------------------
$BUNDLE = @(
    "run.bat",
    "anythingllm_v1.py",
    "launch_anythingllm.bat",
    "launch_anythingllm.ps1",
    "setup_anythingllm.bat",
    "README.md"
)

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
function Write-Step([string]$msg) {
    Write-Host "  [>] $msg" -ForegroundColor Cyan
}
function Write-Ok([string]$msg) {
    Write-Host "  [+] $msg" -ForegroundColor Green
}
function Write-Fail([string]$msg) {
    Write-Host "  [!] $msg" -ForegroundColor Red
}

# ---------------------------------------------------------------------------
# Verify all source files exist
# ---------------------------------------------------------------------------
Write-Host ""
Write-Host "  AnythingLLM Launcher — Pack Tool  v$Version" -ForegroundColor Yellow
Write-Host "  =============================================" -ForegroundColor Yellow
Write-Host ""
Write-Step "Verifying source files ..."

$missing = $false
foreach ($f in $BUNDLE) {
    $full = Join-Path $Root $f
    if (Test-Path $full) {
        Write-Host "    OK  $f" -ForegroundColor DarkGray
    } else {
        Write-Fail "MISSING  $f"
        $missing = $true
    }
}
if ($missing) {
    Write-Fail "One or more source files are missing. Aborting."
    exit 1
}

# ---------------------------------------------------------------------------
# 1. Build ZIP archive
# ---------------------------------------------------------------------------
Write-Host ""
Write-Step "Creating ZIP archive ..."

$ZipPath = Join-Path $OutputDir "$PackageName.zip"
if (Test-Path $ZipPath) { Remove-Item $ZipPath -Force }

Add-Type -AssemblyName System.IO.Compression.FileSystem

$zip = [System.IO.Compression.ZipFile]::Open($ZipPath, 'Create')
foreach ($f in $BUNDLE) {
    $full = Join-Path $Root $f
    [System.IO.Compression.ZipFileExtensions]::CreateEntryFromFile(
        $zip, $full, $f, [System.IO.Compression.CompressionLevel]::Optimal
    ) | Out-Null
}
$zip.Dispose()

Write-Ok "ZIP  →  $ZipPath"

# ---------------------------------------------------------------------------
# 2. Build self-extracting installer
# ---------------------------------------------------------------------------
Write-Host ""
Write-Step "Encoding files for self-extracting installer ..."

# Build a hashtable: filename -> base64 string
$encoded = [ordered]@{}
foreach ($f in $BUNDLE) {
    $bytes         = [System.IO.File]::ReadAllBytes((Join-Path $Root $f))
    $encoded[$f]   = [Convert]::ToBase64String($bytes)
    Write-Host "    encoded  $f  ($($bytes.Length) bytes)" -ForegroundColor DarkGray
}

# Serialize to a PowerShell literal that the installer can eval
$filesLiteral = "@{`n"
foreach ($kv in $encoded.GetEnumerator()) {
    $filesLiteral += "    '$($kv.Key)' = '$($kv.Value)'`n"
}
$filesLiteral += "}"

# ---------------------------------------------------------------------------
# Installer script template
# ---------------------------------------------------------------------------
$installerScript = @"
#Requires -Version 5.1
<#
.SYNOPSIS
    AnythingLLM Launcher  v$Version  — Self-Extracting Installer
    Single-file installer generated by pack.ps1.
    All launcher files are embedded; no internet connection required.
.EXAMPLE
    .\AnythingLLM_Launcher_Setup_v$Version.ps1
    .\AnythingLLM_Launcher_Setup_v$Version.ps1 -InstallDir C:\Tools\AnythingLLM
#>
param(
    [string]`$InstallDir = "",
    [switch]`$NoShortcut,
    [switch]`$Silent
)

Set-StrictMode -Version Latest
`$ErrorActionPreference = "Stop"

# ------------------------------------------------------------------
# Embedded files  (base64-encoded, generated by pack.ps1)
# ------------------------------------------------------------------
`$FILES = $filesLiteral

# ------------------------------------------------------------------
# Helpers
# ------------------------------------------------------------------
function Write-Banner {
    Write-Host ""
    Write-Host "  ============================================================" -ForegroundColor Cyan
    Write-Host "    AnythingLLM Launcher  v$Version  —  Installer" -ForegroundColor Cyan
    Write-Host "  ============================================================" -ForegroundColor Cyan
    Write-Host ""
}

function Check-Prereq([string]`$Name, [string]`$Cmd, [string]`$Url) {
    if (-not (Get-Command `$Cmd -ErrorAction SilentlyContinue)) {
        Write-Host "  [!] `$Name is not installed." -ForegroundColor Red
        Write-Host "      Download: `$Url" -ForegroundColor Yellow
        return `$false
    }
    `$ver = & `$Cmd --version 2>&1 | Select-Object -First 1
    Write-Host "  [+] `$Name  `$ver" -ForegroundColor Green
    return `$true
}

# ------------------------------------------------------------------
# Main
# ------------------------------------------------------------------
Write-Banner

# --- Prerequisite checks ---
Write-Host "  --- Prerequisites ------------------------------------------------" -ForegroundColor Yellow
Write-Host ""
`$ok = `$true
`$ok = (Check-Prereq "Node.js" "node" "https://nodejs.org/")   -and `$ok
`$ok = (Check-Prereq "npm"     "npm"  "https://nodejs.org/")   -and `$ok
Check-Prereq "Python 3" "python" "https://python.org/" | Out-Null
Check-Prereq "yarn"     "yarn"   "https://yarnpkg.com/" | Out-Null   # optional
if (-not `$ok) {
    Write-Host ""
    Write-Host "  [!] Required prerequisites are missing." -ForegroundColor Red
    if (-not `$Silent) {
        Write-Host "      Install Node.js first, then re-run this installer." -ForegroundColor Yellow
        Read-Host "  Press Enter to exit"
    }
    exit 1
}

# --- Choose install directory ---
Write-Host ""
Write-Host "  --- Install Location --------------------------------------------" -ForegroundColor Yellow
Write-Host ""

if (`$InstallDir -eq "") {
    `$default = Join-Path `$env:USERPROFILE "AnythingLLM-Launcher"
    if (-not `$Silent) {
        `$input = Read-Host "  [?] Install directory (blank = `$default)"
        `$InstallDir = if (`$input.Trim() -eq "") { `$default } else { `$input.Trim() }
    } else {
        `$InstallDir = `$default
    }
}

if (-not (Test-Path `$InstallDir)) {
    New-Item -ItemType Directory -Path `$InstallDir -Force | Out-Null
    Write-Host "  [+] Created  `$InstallDir" -ForegroundColor Green
} else {
    Write-Host "  [+] Target   `$InstallDir  (already exists)" -ForegroundColor Green
}

# --- Extract files ---
Write-Host ""
Write-Host "  --- Extracting Files -------------------------------------------" -ForegroundColor Yellow
Write-Host ""
foreach (`$kv in `$FILES.GetEnumerator()) {
    `$dest  = Join-Path `$InstallDir `$kv.Key
    `$bytes = [Convert]::FromBase64String(`$kv.Value)
    [System.IO.File]::WriteAllBytes(`$dest, `$bytes)
    Write-Host "  [+] `$(`$kv.Key)" -ForegroundColor Green
}

# --- Desktop shortcut ---
if (-not `$NoShortcut) {
    `$createShortcut = `$true
    if (-not `$Silent) {
        `$ans = Read-Host "  [?] Create desktop shortcut? (Y/n)"
        `$createShortcut = (`$ans -imatch '^y$|^$')
    }

    if (`$createShortcut) {
        `$wsh      = New-Object -ComObject WScript.Shell
        `$desktop  = `$wsh.SpecialFolders("Desktop")
        `$lnk      = `$wsh.CreateShortcut("`$desktop\AnythingLLM Launcher.lnk")

        # Use pythonw.exe (no console window) if available, else python
        `$pyExe = (Get-Command pythonw -ErrorAction SilentlyContinue)?.Source
        if (-not `$pyExe) { `$pyExe = (Get-Command python -ErrorAction SilentlyContinue)?.Source }
        if (-not `$pyExe) { `$pyExe = "python" }

        `$lnk.TargetPath       = `$pyExe
        `$lnk.Arguments        = "`"`$(Join-Path `$InstallDir 'anythingllm_v1.py')`""
        `$lnk.WorkingDirectory = `$InstallDir
        `$lnk.Description      = "AnythingLLM Launcher v$Version"
        `$lnk.Save()
        Write-Host "  [+] Desktop shortcut created." -ForegroundColor Green
    }
}

# --- Done ---
Write-Host ""
Write-Host "  ============================================================" -ForegroundColor Green
Write-Host "    Installation complete!" -ForegroundColor Green
Write-Host ""
Write-Host "    To launch:  `$InstallDir\run.bat" -ForegroundColor Green
Write-Host "                (or double-click the desktop shortcut)" -ForegroundColor Green
Write-Host ""
Write-Host "    First time? Run setup_anythingllm.bat to install" -ForegroundColor Green
Write-Host "    AnythingLLM itself and its dependencies." -ForegroundColor Green
Write-Host "  ============================================================" -ForegroundColor Green
Write-Host ""

if (-not `$Silent) {
    `$open = Read-Host "  [?] Open install folder now? (Y/n)"
    if (`$open -imatch '^y$|^$') {
        Start-Process explorer.exe `$InstallDir
    }
}
"@

# Write installer
$SetupPath = Join-Path $OutputDir "${PackageName}_Setup.ps1"
[System.IO.File]::WriteAllText($SetupPath, $installerScript, [System.Text.Encoding]::UTF8)

Write-Ok "Installer  →  $SetupPath"

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------
Write-Host ""
Write-Host "  ============================================================" -ForegroundColor Green
Write-Host "    Pack complete  —  $PackageName" -ForegroundColor Green
Write-Host ""
Write-Host "    ZIP        $ZipPath" -ForegroundColor Green
Write-Host "    Installer  $SetupPath" -ForegroundColor Green
Write-Host ""
Write-Host "    Share either file.  The installer is self-contained:" -ForegroundColor DarkGray
Write-Host "    run it on any Windows machine with no other files needed." -ForegroundColor DarkGray
Write-Host "  ============================================================" -ForegroundColor Green
Write-Host ""
